from __future__ import annotations

from finsight.engine.models import RiskAnalysisResult, RiskReport


DISCLAIMER = (
    "\n\n---\n"
    "DISCLAIMER: This report is generated by FinSight AI for informational purposes only. "
    "It does not constitute financial advice, investment advice, or a recommendation to buy, "
    "hold, or sell any security. Always consult a qualified financial adviser before making "
    "investment decisions. Past performance is not indicative of future results."
)


def format_report(result: RiskAnalysisResult) -> str:
    if not result.risk_report:
        return f"FinSight Risk Report\nTicker: {result.ticker}\nStatus: {result.status}\nErrors: {result.errors}"

    rr: RiskReport = result.risk_report
    md = result.provider_payloads.get("market_data")
    market = md.data if md else {}
    validation = result.validation

    text = f"""FinSight Risk Report
Ticker:            {rr.ticker}
Company:           {market.get('company_name', 'N/A')}
Status:            {result.status}
Risk Level:        {rr.risk_level.upper()}
Composite Score:   {rr.composite_score} / 100
Recommendation:    {rr.recommendation}

Summary
--------
{rr.summary}

Market Data
-----------
Current Price:     ${market.get('current_price', 'N/A')}
52-Week High:      ${market.get('52_week_high', 'N/A')}
52-Week Low:       ${market.get('52_week_low', 'N/A')}
Historical Vol:    {rr.volatility_pct}%
Implied Vol:       {rr.implied_vol_pct or 'N/A'}%
P/E Ratio:         {rr.pe_ratio}

Fundamentals
------------
Debt/Equity:       {rr.debt_to_equity or 'N/A'}

Sentiment & Macro
-----------------
Sentiment Score:   {rr.sentiment_score if rr.sentiment_score is not None else 'N/A'}
Dominant Theme:    {rr.dominant_theme or 'N/A'}
Market Regime:     {rr.market_regime or 'N/A'}

Validation
----------
Deterministic:     {'passed' if validation.deterministic_check_passed else 'failed'}
Flags:             {validation.deterministic_flags}
Data Quality:      {rr.data_quality}
"""
    if rr.mda_excerpt:
        text += f"\nMD&A Grounding\n--------------\n{rr.mda_excerpt[:600]}\n"
    if result.errors:
        text += f"\nErrors\n------\n" + "\n".join(f"- {error}" for error in result.errors)
    return text + DISCLAIMER
