# from __future__ import annotations

# import concurrent.futures
# import json
# import time
# from typing import Any

# from langgraph.graph import StateGraph, END
# from typing_extensions import TypedDict

# from finsight.config import Settings
# from finsight.data.macro import get_macro_context
# from finsight.data.market import get_market_data, get_options_iv
# from finsight.data.news import get_news_sentiment
# from finsight.data.sec import get_sec_filings
# from finsight.engine.cost import CostTracker
# from finsight.engine.persistence import compute_composite_trend, save_report, chroma_store_report
# from finsight.engine.models import (
#     BiasReport,
#     HallucinationReport,
#     JudgeScore,
#     ProviderPayload,
#     QuantData,
#     RiskAnalysisResult,
#     RiskReport,
#     SourceRef,
#     ValidationResult,
# )
# from finsight.engine.scoring import (
#     compute_composite_score,
#     recommendation_from_score,
#     risk_level_from_score,
#     score_breakdown,
# )
# from finsight.engine.validation import (
#     deterministic_hallucination_check,
#     qualitative_hallucination_check,
# )
# from finsight.llm.client import call_llm_json, get_llm_client
# from finsight.reports.formatter import format_report


# JUDGE_THRESHOLD = 4
# MAX_REFINEMENT_ITERS = 2

# PROHIBITED_CLAIMS = [
#     "guaranteed return", "risk-free", "certain to", "will definitely"
# ]

# DISCLAIMER = (
#     "\n\n---\n"
#     "DISCLAIMER: This report is generated by FinSight AI for informational purposes only. "
#     "It does not constitute financial advice, investment advice, or a recommendation to buy, "
#     "hold, or sell any security. Always consult a qualified financial adviser before making "
#     "investment decisions. Past performance is not indicative of future results.\n"
# )


# # ── Compliance filter ──────────────────────────────────────────────────────
# def apply_compliance_filter(report_text: str) -> tuple[str, list[str]]:
#     redacted = []
#     for phrase in PROHIBITED_CLAIMS:
#         if phrase.lower() in report_text.lower():
#             report_text = report_text.replace(phrase, "[REDACTED]")
#             redacted.append(phrase)
#     return report_text + DISCLAIMER, redacted


# # ── LangGraph state ────────────────────────────────────────────────────────
# class FinSightState(TypedDict):
#     ticker: str
#     settings: Any
#     cost: Any
#     llm: Any
#     market_data: dict
#     iv_data: dict
#     fundamentals_data: dict
#     news_sentiment_data: dict
#     macro_data: dict
#     quant_data: dict
#     risk_report: dict
#     judge_score: dict
#     hallucination_report: dict
#     bias_report: dict
#     refinement_iter: int
#     final_report_text: str
#     errors: list
#     provider_payloads: dict


# # ── Node 1: Parallel data collection ──────────────────────────────────────
# def node_collect_data(state: FinSightState) -> FinSightState:
#     ticker = state["ticker"]
#     settings = state["settings"]
#     cost = state["cost"]
#     llm = state["llm"]
#     print(f"  [collect_data] Fetching data for {ticker} in parallel...")
#     t0 = time.time()

#     tasks = {
#         "market_data":         (get_market_data, (ticker,)),
#         "iv_data":             (get_options_iv, (ticker,)),
#         "fundamentals_data":   (get_sec_filings, (ticker, settings, "10-K", True)),
#         "news_sentiment_data": (get_news_sentiment, (ticker, settings, cost, llm)),
#         "macro_data":          (get_macro_context, ()),
#     }
#     results: dict[str, ProviderPayload] = {}
#     errors: list[str] = []

#     with concurrent.futures.ThreadPoolExecutor(max_workers=5) as executor:
#         futures = {
#             executor.submit(fn, *args): name
#             for name, (fn, args) in tasks.items()
#         }
#         for future in concurrent.futures.as_completed(futures):
#             name = futures[future]
#             try:
#                 results[name] = future.result()
#             except Exception as exc:
#                 results[name] = ProviderPayload(status="error", error_message=str(exc))
#                 errors.append(f"{name}: {exc}")

#     print(f"  [collect_data] Done in {time.time()-t0:.1f}s")

#     ordered = {name: results[name] for name in tasks}
#     updates = {name: payload.model_dump() for name, payload in ordered.items()}
#     updates["provider_payloads"] = ordered
#     updates["errors"] = state["errors"] + errors
#     return {**state, **updates}


# # ── Node 2: Quant strategy signals ────────────────────────────────────────
# def node_quant_strategy(state: FinSightState) -> FinSightState:
#     settings = state["settings"]
#     cost = state["cost"]
#     market = state["market_data"].get("data", {})
#     macro = state["macro_data"].get("data", {})
#     print("  [quant_strategy] Computing RSI / momentum / macro overlay...")

#     # Deterministic fallback
#     price = market.get("current_price") or 0
#     high = market.get("52_week_high") or price
#     low = market.get("52_week_low") or price
#     rsi_signal = momentum_signal = macro_adjusted_signal = "neutral"
#     technical_summary = "Technical signal unavailable."

#     if price and high > low:
#         ratio = (price - low) / (high - low) * 100
#         rsi_signal = "overbought" if ratio >= 70 else "oversold" if ratio <= 30 else "neutral"
#         midpoint = low + (high - low) / 2
#         momentum_signal = "positive" if price > midpoint else "negative" if price != midpoint else "neutral"
#         regime = macro.get("market_regime", "neutral")
#         if regime == "risk-on" and momentum_signal == "positive":
#             macro_adjusted_signal = "positive"
#         elif regime == "risk-off" and momentum_signal == "negative":
#             macro_adjusted_signal = "negative"
#         else:
#             macro_adjusted_signal = "caution" if regime == "neutral" else momentum_signal
#         technical_summary = (
#             f"RSI signal is {rsi_signal}, momentum is {momentum_signal}, "
#             f"and macro-adjusted signal is {macro_adjusted_signal}."
#         )

#     llm_result: dict = {}
#     try:
#         if settings.groq_api_key and not cost.budget_exceeded:
#             system = "You are a quantitative analyst. Compute technical signals from the data provided."
#             user = f"""
# Market data: {json.dumps(market)}
# Macro data:  {json.dumps(macro)}

# Compute:
# 1. RSI classification using 52-week high/low and current price:
#    - current_price > 0.90 * 52_week_high → 'overbought'
#    - current_price < 1.10 * 52_week_low  → 'oversold'
#    - Otherwise → 'neutral'
# 2. momentum_signal: 'strong' if near high, 'weak' if near low, 'neutral' otherwise
# 3. macro_adjusted_signal: shift momentum in direction of market_regime
# 4. technical_summary: one sentence combining all signals

# Return JSON: {{"rsi_signal": str, "momentum_signal": str, "macro_adjusted_signal": str, "technical_summary": str}}
# """
#             llm_result = call_llm_json(system, user, QuantData, settings, cost)
#     except Exception:
#         pass

#     quant = llm_result if llm_result else {
#         "rsi_signal": rsi_signal,
#         "momentum_signal": momentum_signal,
#         "macro_adjusted_signal": macro_adjusted_signal,
#         "technical_summary": technical_summary,
#     }
#     return {**state, "quant_data": quant}


# # ── Node 3: Risk synthesis ─────────────────────────────────────────────────
# def node_risk_synthesis(state: FinSightState) -> FinSightState:
#     settings = state["settings"]
#     cost = state["cost"]
#     ticker = state["ticker"]
#     print("  [risk_synthesis] Synthesising risk report...")

#     market = state["market_data"].get("data", {})
#     iv = state["iv_data"].get("data", {})
#     fund = state["fundamentals_data"].get("data", {})
#     news = state["news_sentiment_data"].get("data", {})
#     mac = state["macro_data"].get("data", {})
#     qnt = state.get("quant_data", {})

#     price = market.get("current_price") or 1
#     hi = market.get("52_week_high") or price
#     lo = market.get("52_week_low") or price
#     vol_pct = round((hi - lo) / price * 100, 2)
#     iv_pct = iv.get("iv_annualised_pct")
#     d_e = fund.get("debt_to_equity")
#     sent = news.get("sentiment_score")
#     regime = mac.get("market_regime")
#     composite = compute_composite_score(vol_pct, iv_pct, d_e, sent, regime)
#     composite_trend = compute_composite_trend(ticker, composite)
#     print(f"  [risk_synthesis] Composite trend: {composite_trend}")

#     mda_excerpt = fund.get("mda_excerpt", "")
#     mda_section = ""
#     if mda_excerpt and not str(mda_excerpt).startswith("[MD&A"):
#         mda_section = f"""
# Management Discussion & Analysis (MD&A) excerpt from latest 10-K:
# --- BEGIN MD&A ---
# {mda_excerpt[:1500]}
# --- END MD&A ---
# Use language from the MD&A to ground qualitative risk statements where relevant.
# """

#     available = sum([
#         state["market_data"].get("status") == "success",
#         state["iv_data"].get("status") == "success",
#         state["fundamentals_data"].get("status") == "success",
#         state["news_sentiment_data"].get("status") in ("success", "skipped"),
#         state["macro_data"].get("status") == "success",
#     ])
#     data_quality = "full" if available == 5 else "partial" if available >= 3 else "minimal"

#     headline_summary = ""
#     if news.get("label_counts"):
#         headline_summary = (
#             f"Headline label counts: {json.dumps(news.get('label_counts', {}))}. "
#             f"Dominant label: {news.get('dominant_label', 'N/A')}."
#         )

#     llm_result: dict | None = None
#     try:
#         if settings.groq_api_key and not cost.budget_exceeded:
#             system = "You are a senior financial risk analyst. Produce a structured risk report in JSON."
#             user = f"""
# Ticker: {ticker}
# Market data:     {json.dumps(market)}
# Options IV:      {json.dumps(iv)}
# Fundamentals:    {json.dumps(fund)}
# News sentiment:  {json.dumps({k:v for k,v in news.items() if k != 'classifications'})}
# {headline_summary}
# Macro context:   {json.dumps(mac)}
# Quant signals:   {json.dumps(qnt)}
# {mda_section}
# Pre-computed values (use these exactly):
#   volatility_pct:  {vol_pct}
#   composite_score: {composite}  (0-100, >60=high, 30-60=moderate, <30=low)
#   composite_trend: {composite_trend}
#   data_quality:    {data_quality}

# Produce a RiskReport JSON with ALL of these fields:
#   ticker, risk_level (low/moderate/high), volatility_pct, pe_ratio (number or 'N/A'),
#   summary (one sentence, ground in MD&A language where available),
#   recommendation (hold/watch/avoid),
#   implied_vol_pct, debt_to_equity, sentiment_score, dominant_theme,
#   market_regime, composite_score, data_quality,
#   composite_trend (copy the pre-computed string exactly),
#   mda_excerpt (key phrase from MD&A that supports your summary, or null)

# Use pre-computed volatility_pct and composite_score exactly.
# risk_level: <30=low, 30-60=moderate, >60=high
# recommendation: hold=low risk, watch=moderate, avoid=high
# """
#             llm_result = call_llm_json(system, user, RiskReport, settings, cost)
#     except Exception:
#         pass

#     if llm_result:
#         llm_result["composite_trend"] = composite_trend
#         state = {**state, "risk_report": llm_result}
#     else:
#         # Deterministic fallback
#         fallback = RiskReport(
#             ticker=ticker,
#             risk_level=risk_level_from_score(composite),
#             volatility_pct=vol_pct,
#             pe_ratio=market.get("pe_ratio"),
#             summary=(
#                 f"{ticker} screens as {risk_level_from_score(composite)} risk with composite "
#                 f"score {composite}/100, driven by {vol_pct}% 52-week range volatility and a "
#                 f"{regime or 'unknown'} macro regime."
#             ),
#             recommendation=recommendation_from_score(composite),
#             implied_vol_pct=iv_pct,
#             debt_to_equity=d_e,
#             sentiment_score=sent,
#             dominant_theme=news.get("dominant_label") or news.get("sentiment_label"),
#             market_regime=regime,
#             composite_score=composite,
#             data_quality=data_quality,
#             composite_trend=composite_trend,
#             mda_excerpt=fund.get("mda_excerpt"),
#         )
#         state = {**state, "risk_report": fallback.model_dump()}

#     return state


# # ── Node 4: Judge ──────────────────────────────────────────────────────────
# def node_judge(state: FinSightState) -> FinSightState:
#     settings = state["settings"]
#     cost = state["cost"]
#     if cost.budget_exceeded or not settings.groq_api_key:
#         return {**state, "judge_score": {"score": 3, "reasoning": "Judge skipped."}}

#     print("  [judge] Scoring report quality...")
#     system = "You are a quality judge for AI-generated financial reports."
#     user = f"""
# Score this risk report on a scale of 1-5 (5=excellent).
# Criteria: completeness, internal consistency, actionability, grounding in data.

# Report: {json.dumps(state['risk_report'])}

# Return JSON: {{"score": <int 1-5>, "reasoning": "<one sentence>"}}
# """
#     result = call_llm_json(system, user, JudgeScore, settings, cost)
#     if not result:
#         result = {"score": 3, "reasoning": "Judge unavailable."}
#     print(f"  [judge] Score: {result.get('score')}/5 — {result.get('reasoning')}")
#     return {**state, "judge_score": result}


# # ── Routing ────────────────────────────────────────────────────────────────
# def route_after_judge(state: FinSightState) -> str:
#     cost = state["cost"]
#     if cost.budget_exceeded:
#         print("  [router] Budget exceeded → finalize")
#         return "finalize"
#     score = int(state["judge_score"].get("score", 3))
#     iters = int(state.get("refinement_iter", 0))
#     if score >= JUDGE_THRESHOLD:
#         return "hallucination_check"
#     if score == 1 or iters >= MAX_REFINEMENT_ITERS:
#         print(f"  [router] Score={score}, iters={iters} → finalize")
#         return "finalize"
#     print(f"  [router] Score={score} below threshold → refining (iter {iters+1})")
#     return "refine_report"


# # ── Node 5: Refine ─────────────────────────────────────────────────────────
# def node_refine_report(state: FinSightState) -> FinSightState:
#     settings = state["settings"]
#     cost = state["cost"]
#     if cost.budget_exceeded:
#         return state
#     iter_n = state.get("refinement_iter", 0) + 1
#     print(f"  [refine_report] Refinement iteration {iter_n}...")
#     system = "You are an expert financial analyst. Improve the risk report based on feedback."
#     user = f"""
# Original report:      {json.dumps(state['risk_report'])}
# Judge feedback:       {json.dumps(state['judge_score'])}
# Hallucination report: {json.dumps(state.get('hallucination_report', {}))}
# Bias report:          {json.dumps(state.get('bias_report', {}))}

# Improve the report to address all flagged issues. Keep the same JSON schema.
# recommendation must be one of: hold, watch, avoid
# data_quality must be one of: full, partial, minimal  (do NOT use 'complete' or any other value)
# The composite_trend field must stay exactly as-is.

# Return an improved RiskReport JSON with the same fields.
# """
#     result = call_llm_json(system, user, RiskReport, settings, cost)
#     if result:
#         # Pin fields that must not change during refinement
#         if state["risk_report"].get("composite_trend"):
#             result["composite_trend"] = state["risk_report"]["composite_trend"]
#         # Normalise data_quality in case the LLM returns a synonym (e.g. "complete")
#         _DQ_MAP = {"complete": "full", "good": "full", "none": "minimal", "low": "minimal"}
#         dq = result.get("data_quality", "")
#         if dq not in ("full", "partial", "minimal"):
#             result["data_quality"] = _DQ_MAP.get(dq.lower(), state["risk_report"].get("data_quality", "partial"))
#         state = {**state, "risk_report": result}
#     return {**state, "refinement_iter": iter_n}


# # ── Node 6: Hallucination check ────────────────────────────────────────────
# def node_hallucination_check(state: FinSightState) -> FinSightState:
#     settings = state["settings"]
#     cost = state["cost"]
#     print("  [hallucination_check] Running deterministic pre-check...")

#     det = deterministic_hallucination_check(
#         risk_report=state["risk_report"],
#         market_data=state["market_data"],
#         iv_data=state["iv_data"],
#         fundamentals_data=state["fundamentals_data"],
#         news_sentiment_data=state["news_sentiment_data"],
#         macro_data=state["macro_data"],
#     )

#     llm_result = qualitative_hallucination_check(state, settings, cost)
#     combined = {
#         "has_hallucination": not det.deterministic_check_passed or llm_result.get("has_hallucination", False),
#         "flagged_claims": llm_result.get("flagged_claims", []),
#         "confidence": llm_result.get("confidence", "high"),
#         "deterministic_flags": det.deterministic_flags,
#         "deterministic_check_passed": det.deterministic_check_passed,
#     }
#     if combined["has_hallucination"]:
#         print(f"  ⚠ Hallucination detected. Det: {det.deterministic_flags}. LLM: {llm_result.get('flagged_claims')}")
#     return {**state, "hallucination_report": combined}


# # ── Node 7: Bias audit ─────────────────────────────────────────────────────
# def node_bias_audit(state: FinSightState) -> FinSightState:
#     settings = state["settings"]
#     cost = state["cost"]
#     if cost.budget_exceeded:
#         return state
#     print("  [bias_audit] Checking for sentiment-driven bias...")
#     system = "You are a bias auditor for AI-generated financial risk assessments."
#     user = f"""
# Risk report:    {json.dumps(state['risk_report'])}
# News sentiment: {json.dumps({k:v for k,v in state['news_sentiment_data'].get('data', {}).items() if k != 'classifications'})}
# Fundamentals:   {json.dumps(state['fundamentals_data'].get('data', {}))}

# Flag sentiment_bias_detected=true if the recommendation aligns with sentiment_score direction
# but contradicts the fundamentals (e.g. 'watch' with negative sentiment but strong financials).

# Return JSON: {{"sentiment_bias_detected": bool, "reasoning": "<one sentence>"}}
# """
#     result = call_llm_json(system, user, BiasReport, settings, cost)
#     return {**state, "bias_report": result or {"sentiment_bias_detected": False, "reasoning": "Bias audit skipped."}}


# # ── Node 8: Finalize ───────────────────────────────────────────────────────
# def node_finalize(state: FinSightState) -> FinSightState:
#     print("  [finalize] Applying final deterministic gate, compliance filter...")
#     rr = state.get("risk_report", {})
#     js = state.get("judge_score", {})
#     qd = state.get("quant_data", {})
#     hr = state.get("hallucination_report", {})
#     br = state.get("bias_report", {})

#     if rr:
#         final_det = deterministic_hallucination_check(
#             risk_report=rr,
#             market_data=state["market_data"],
#             iv_data=state["iv_data"],
#             fundamentals_data=state["fundamentals_data"],
#             news_sentiment_data=state["news_sentiment_data"],
#             macro_data=state["macro_data"],
#         )
#         existing_flags = hr.get("deterministic_flags", [])
#         merged_flags = list(dict.fromkeys(existing_flags + final_det.deterministic_flags))
#         hr = {
#             **hr,
#             "deterministic_check_passed": final_det.deterministic_check_passed,
#             "deterministic_flags": merged_flags,
#             "has_hallucination": hr.get("has_hallucination", False) or not final_det.deterministic_check_passed,
#         }

#     md = state["market_data"].get("data", {})
#     mac = state["macro_data"].get("data", {})
#     risk_emoji = {"low": "🟢", "moderate": "🟡", "high": "🔴"}.get(rr.get("risk_level", ""), "⚪")
#     det_status = "✓ Passed" if hr.get("deterministic_check_passed", True) else f"⚠ Failed: {hr.get('deterministic_flags', [])}"

#     report_text = f"""FinSight v2 Enhanced Risk Report
# {'='*55}
# Ticker:            {rr.get('ticker')}
# Company:           {md.get('company_name', 'N/A')}
# Risk Level:        {risk_emoji} {rr.get('risk_level', '').upper()}
# Composite Score:   {rr.get('composite_score')} / 100
# Composite Trend:   {rr.get('composite_trend', 'N/A')}
# Recommendation:    {rr.get('recommendation', '').upper()}

# Summary
# {'-'*40}
# {rr.get('summary')}

# {'MD&A Grounding' if rr.get('mda_excerpt') else ''}
# {('-'*40) if rr.get('mda_excerpt') else ''}
# {rr.get('mda_excerpt', '') if rr.get('mda_excerpt') else ''}

# Market Data
# {'-'*40}
# Current Price:     ${md.get('current_price', 'N/A')}
# 52-Week High:      ${md.get('52_week_high', 'N/A')}
# 52-Week Low:       ${md.get('52_week_low', 'N/A')}
# Historical Vol:    {rr.get('volatility_pct')}%
# Implied Vol:       {rr.get('implied_vol_pct', 'N/A')}%
# P/E Ratio:         {rr.get('pe_ratio', 'N/A')}

# Fundamentals
# {'-'*40}
# Debt/Equity:       {rr.get('debt_to_equity', 'N/A')}

# Sentiment & Macro
# {'-'*40}
# Sentiment Score:   {rr.get('sentiment_score', 'N/A')} (-1 bearish → +1 bullish)
# Sentiment Method:  {state['news_sentiment_data'].get('data', {}).get('method', 'N/A')}
# Dominant Theme:    {rr.get('dominant_theme', 'N/A')}
# Market Regime:     {rr.get('market_regime', 'N/A')}
# VIX:               {mac.get('vix', 'N/A')}
# 10Y Yield:         {mac.get('ten_year_yield_pct', 'N/A')}%

# Quant Signals
# {'-'*40}
# RSI Signal:        {qd.get('rsi_signal', 'N/A')}
# Momentum:          {qd.get('momentum_signal', 'N/A')}
# Macro-Adjusted:    {qd.get('macro_adjusted_signal', 'N/A')}
# Technical Note:    {qd.get('technical_summary', 'N/A')}

# Evaluation
# {'-'*40}
# Judge Score:       {js.get('score')}/5
# Judge Reasoning:   {js.get('reasoning')}
# Det. Pre-check:    {det_status}
# Hallucination:     {'⚠ Detected' if hr.get('has_hallucination') else '✓ None detected'}
# Bias Audit:        {'⚠ Bias detected' if br.get('sentiment_bias_detected') else '✓ No bias detected'}
# Bias Reasoning:    {br.get('reasoning', 'N/A')}
# Data Quality:      {rr.get('data_quality', 'N/A')}
# Refinement Iters:  {state.get('refinement_iter', 0)}
# Sentiment Method:  {state['news_sentiment_data'].get('data', {}).get('method', 'N/A')}
# """
#     report_text, redacted = apply_compliance_filter(report_text)
#     if redacted:
#         report_text += f"\n[Compliance: redacted {redacted}]"

#     return {**state, "hallucination_report": hr, "final_report_text": report_text}


# # ── Build LangGraph ────────────────────────────────────────────────────────
# def _build_graph():
#     builder = StateGraph(FinSightState)
#     builder.add_node("collect_data",        node_collect_data)
#     builder.add_node("quant_strategy",      node_quant_strategy)
#     builder.add_node("risk_synthesis",      node_risk_synthesis)
#     builder.add_node("judge",               node_judge)
#     builder.add_node("refine_report",       node_refine_report)
#     builder.add_node("hallucination_check", node_hallucination_check)
#     builder.add_node("bias_audit",          node_bias_audit)
#     builder.add_node("finalize",            node_finalize)

#     builder.set_entry_point("collect_data")
#     builder.add_edge("collect_data",   "quant_strategy")
#     builder.add_edge("quant_strategy", "risk_synthesis")
#     builder.add_edge("risk_synthesis", "judge")
#     builder.add_conditional_edges(
#         "judge",
#         route_after_judge,
#         {
#             "hallucination_check": "hallucination_check",
#             "refine_report":       "refine_report",
#             "finalize":            "finalize",
#         },
#     )
#     builder.add_edge("refine_report",       "judge")
#     builder.add_edge("hallucination_check", "bias_audit")
#     builder.add_edge("bias_audit",          "finalize")
#     builder.add_edge("finalize",            END)
#     return builder.compile()


# _graph = None

# def _get_graph():
#     global _graph
#     if _graph is None:
#         _graph = _build_graph()
#     return _graph


# # ── Public entry point ─────────────────────────────────────────────────────
# def run_finsight_analysis(ticker: str, settings: Settings | None = None) -> RiskAnalysisResult:
#     settings = settings or Settings()
#     cost = CostTracker(settings.cost_budget_usd)
#     ticker = ticker.upper().strip()
#     llm = get_llm_client(settings) if settings.groq_api_key else None

#     initial_state: FinSightState = {
#         "ticker": ticker,
#         "settings": settings,
#         "cost": cost,
#         "llm": llm,
#         "market_data": {},
#         "iv_data": {},
#         "fundamentals_data": {},
#         "news_sentiment_data": {},
#         "macro_data": {},
#         "quant_data": {},
#         "risk_report": {},
#         "judge_score": {},
#         "hallucination_report": {},
#         "bias_report": {},
#         "refinement_iter": 0,
#         "final_report_text": "",
#         "errors": [],
#         "provider_payloads": {},
#     }

#     graph = _get_graph()
#     final_state = graph.invoke(initial_state)

#     try:
#         save_report(
#             final_state["ticker"],
#             final_state["risk_report"],
#             final_state.get("judge_score", {}),
#             token_cost=cost.input_tokens + cost.output_tokens,
#         )
#         try:
#             chroma_store_report(final_state["ticker"], final_state["risk_report"])
#         except Exception:
#             pass
#     except Exception as exc:
#         final_state["errors"].append(f"persistence: {exc}")

#     report = RiskReport(**final_state["risk_report"])
#     data_quality = report.data_quality
#     status = "success" if data_quality == "full" and not final_state["errors"] else "partial"
#     if final_state["market_data"].get("status") == "error":
#         status = "failed"

#     result = RiskAnalysisResult(
#         ticker=ticker,
#         status=status,
#         data_quality=data_quality,
#         metrics=_metrics_from_report(report),
#         risk_report=report,
#         quant_data=QuantData(**final_state["quant_data"]) if final_state.get("quant_data") else None,
#         judge_score=JudgeScore(**final_state["judge_score"]) if final_state.get("judge_score") else None,
#         hallucination_report=HallucinationReport(**final_state["hallucination_report"]) if final_state.get("hallucination_report") else None,
#         bias_report=BiasReport(**final_state["bias_report"]) if final_state.get("bias_report") else None,
#         validation=ValidationResult(**final_state["hallucination_report"]) if final_state.get("hallucination_report") else ValidationResult(),
#         sources=_sources_from_payloads(final_state.get("provider_payloads", {})),
#         provider_payloads=final_state.get("provider_payloads", {}),
#         errors=final_state["errors"],
#         cost=cost.summary(),
#     )
#     result.final_report_text = final_state.get("final_report_text", "")
#     return result


# def _metrics_from_report(report: RiskReport) -> dict[str, Any]:
#     return {
#         "volatility_pct": report.volatility_pct,
#         "implied_vol_pct": report.implied_vol_pct,
#         "debt_to_equity": report.debt_to_equity,
#         "sentiment_score": report.sentiment_score,
#         "market_regime": report.market_regime,
#         "composite_score": report.composite_score,
#         "risk_level": report.risk_level,
#         "score_breakdown": score_breakdown(
#             report.volatility_pct,
#             report.implied_vol_pct,
#             report.debt_to_equity,
#             report.sentiment_score,
#             report.market_regime,
#         ),
#     }


# def _sources_from_payloads(payloads: dict[str, ProviderPayload]) -> list[SourceRef]:
#     sources = [SourceRef(name="Yahoo Finance", metadata={"providers": ["market", "options"]})]
#     sec = payloads.get("fundamentals_data", ProviderPayload(status="skipped")).data
#     if sec.get("filing_url"):
#         sources.append(SourceRef(
#             name="SEC EDGAR",
#             url=sec["filing_url"],
#             metadata={
#                 "cik": sec.get("cik"),
#                 "accession_number": sec.get("accession_number"),
#                 "file_date": sec.get("file_date"),
#                 "period_of_report": sec.get("period_of_report"),
#             },
#         ))
#     news = payloads.get("news_sentiment_data", ProviderPayload(status="skipped"))
#     if news.status == "success":
#         sources.append(SourceRef(name="GNews", metadata={"method": news.data.get("method")}))
#     sources.append(SourceRef(name="Yahoo Finance", metadata={"providers": ["macro"]}))
#     return sources

from __future__ import annotations

import concurrent.futures
import json
import time
from typing import Any

from langgraph.graph import StateGraph, END
from typing_extensions import TypedDict

from finsight.config import Settings
from finsight.data.macro import get_macro_context
from finsight.data.market import get_market_data, get_options_iv
from finsight.data.news import get_news_sentiment
from finsight.data.sec import get_sec_filings
from finsight.engine.cost import CostTracker
from finsight.engine.persistence import compute_composite_trend, save_report, chroma_store_report
from finsight.engine.models import (
    BiasReport,
    HallucinationReport,
    JudgeScore,
    ProviderPayload,
    QuantData,
    RiskAnalysisResult,
    RiskReport,
    SourceRef,
    ValidationResult,
)
from finsight.engine.scoring import (
    compute_composite_score,
    recommendation_from_score,
    risk_level_from_score,
    score_breakdown,
)
from finsight.engine.validation import (
    deterministic_hallucination_check,
    qualitative_hallucination_check,
)
from finsight.llm.client import call_llm_json, get_llm_client
from finsight.reports.formatter import format_report


JUDGE_THRESHOLD = 4
MAX_REFINEMENT_ITERS = 2

PROHIBITED_CLAIMS = [
    "guaranteed return", "risk-free", "certain to", "will definitely"
]

DISCLAIMER = (
    "\n\n---\n"
    "DISCLAIMER: This report is generated by FinSight AI for informational purposes only. "
    "It does not constitute financial advice, investment advice, or a recommendation to buy, "
    "hold, or sell any security. Always consult a qualified financial adviser before making "
    "investment decisions. Past performance is not indicative of future results.\n"
)


# ── Compliance filter ──────────────────────────────────────────────────────
def apply_compliance_filter(report_text: str) -> tuple[str, list[str]]:
    redacted = []
    for phrase in PROHIBITED_CLAIMS:
        if phrase.lower() in report_text.lower():
            report_text = report_text.replace(phrase, "[REDACTED]")
            redacted.append(phrase)
    return report_text + DISCLAIMER, redacted


# ── LangGraph state ────────────────────────────────────────────────────────
class FinSightState(TypedDict):
    ticker: str
    settings: Any
    cost: Any
    llm: Any
    market_data: dict
    iv_data: dict
    fundamentals_data: dict
    news_sentiment_data: dict
    macro_data: dict
    quant_data: dict
    risk_report: dict
    judge_score: dict
    hallucination_report: dict
    bias_report: dict
    refinement_iter: int
    final_report_text: str
    errors: list
    provider_payloads: dict


# ── Node 1: Parallel data collection ──────────────────────────────────────
def node_collect_data(state: FinSightState) -> FinSightState:
    ticker = state["ticker"]
    settings = state["settings"]
    cost = state["cost"]
    llm = state["llm"]
    print(f"  [collect_data] Fetching data for {ticker} in parallel...")
    t0 = time.time()

    tasks = {
        "market_data":         (get_market_data, (ticker,)),
        "iv_data":             (get_options_iv, (ticker,)),
        "fundamentals_data":   (get_sec_filings, (ticker, settings, "10-K", True)),
        "news_sentiment_data": (get_news_sentiment, (ticker, settings, cost, llm)),
        "macro_data":          (get_macro_context, ()),
    }
    results: dict[str, ProviderPayload] = {}
    errors: list[str] = []

    with concurrent.futures.ThreadPoolExecutor(max_workers=5) as executor:
        futures = {
            executor.submit(fn, *args): name
            for name, (fn, args) in tasks.items()
        }
        for future in concurrent.futures.as_completed(futures):
            name = futures[future]
            try:
                results[name] = future.result()
            except Exception as exc:
                results[name] = ProviderPayload(status="error", error_message=str(exc))
                errors.append(f"{name}: {exc}")

    print(f"  [collect_data] Done in {time.time()-t0:.1f}s")

    ordered = {name: results[name] for name in tasks}
    updates = {name: payload.model_dump() for name, payload in ordered.items()}
    updates["provider_payloads"] = ordered
    updates["errors"] = state["errors"] + errors
    return {**state, **updates}


# ── Node 2: Quant strategy signals ────────────────────────────────────────
def node_quant_strategy(state: FinSightState) -> FinSightState:
    market = state["market_data"].get("data", {})
    macro = state["macro_data"].get("data", {})
    print("  [quant_strategy] Computing RSI / momentum / macro overlay...")

    price = market.get("current_price") or 0
    high = market.get("52_week_high") or price
    low = market.get("52_week_low") or price
    rsi_signal = momentum_signal = macro_adjusted_signal = "neutral"
    technical_summary = "Technical signal unavailable."

    if price and high > low:
        ratio = (price - low) / (high - low) * 100
        rsi_signal = "overbought" if ratio >= 70 else "oversold" if ratio <= 30 else "neutral"
        midpoint = low + (high - low) / 2
        momentum_signal = "positive" if price > midpoint else "negative" if price != midpoint else "neutral"
        regime = macro.get("market_regime", "neutral")
        if regime == "risk-on" and momentum_signal == "positive":
            macro_adjusted_signal = "positive"
        elif regime == "risk-off" and momentum_signal == "negative":
            macro_adjusted_signal = "negative"
        else:
            macro_adjusted_signal = "caution" if regime == "neutral" else momentum_signal
        technical_summary = (
            f"RSI signal is {rsi_signal}, momentum is {momentum_signal}, "
            f"and macro-adjusted signal is {macro_adjusted_signal}."
        )

    quant = {
        "rsi_signal": rsi_signal,
        "momentum_signal": momentum_signal,
        "macro_adjusted_signal": macro_adjusted_signal,
        "technical_summary": technical_summary,
    }
    return {**state, "quant_data": quant}


# ── Node 3: Risk synthesis ─────────────────────────────────────────────────
def node_risk_synthesis(state: FinSightState) -> FinSightState:
    settings = state["settings"]
    cost = state["cost"]
    ticker = state["ticker"]
    print("  [risk_synthesis] Synthesising risk report...")

    market = state["market_data"].get("data", {})
    iv = state["iv_data"].get("data", {})
    fund = state["fundamentals_data"].get("data", {})
    news = state["news_sentiment_data"].get("data", {})
    mac = state["macro_data"].get("data", {})
    qnt = state.get("quant_data", {})

    price = market.get("current_price") or 1
    hi = market.get("52_week_high") or price
    lo = market.get("52_week_low") or price
    vol_pct = round((hi - lo) / price * 100, 2)
    iv_pct = iv.get("iv_annualised_pct")
    d_e = fund.get("debt_to_equity")
    sent = news.get("sentiment_score")
    regime = mac.get("market_regime")
    composite = compute_composite_score(vol_pct, iv_pct, d_e, sent, regime)
    composite_trend = compute_composite_trend(ticker, composite)
    print(f"  [risk_synthesis] Composite trend: {composite_trend}")

    mda_excerpt = fund.get("mda_excerpt", "")
    mda_section = ""
    if mda_excerpt and not str(mda_excerpt).startswith("[MD&A"):
        mda_section = f"""
Management Discussion & Analysis (MD&A) excerpt from latest 10-K:
--- BEGIN MD&A ---
{mda_excerpt[:1500]}
--- END MD&A ---
Use language from the MD&A to ground qualitative risk statements where relevant.
"""

    available = sum([
        state["market_data"].get("status") == "success",
        state["iv_data"].get("status") == "success",
        state["fundamentals_data"].get("status") == "success",
        state["news_sentiment_data"].get("status") in ("success", "skipped"),
        state["macro_data"].get("status") == "success",
    ])
    data_quality = "full" if available == 5 else "partial" if available >= 3 else "minimal"

    headline_summary = ""
    if news.get("label_counts"):
        headline_summary = (
            f"Headline label counts: {json.dumps(news.get('label_counts', {}))}. "
            f"Dominant label: {news.get('dominant_label', 'N/A')}."
        )

    llm_result: dict | None = None
    try:
        if settings.groq_api_key and not cost.budget_exceeded:
            system = "You are a senior financial risk analyst. Produce a structured risk report in JSON."
            user = f"""
Ticker: {ticker}
Market data:     {json.dumps(market)}
Options IV:      {json.dumps(iv)}
Fundamentals:    {json.dumps(fund)}
News sentiment:  {json.dumps({k:v for k,v in news.items() if k != 'classifications'})}
{headline_summary}
Macro context:   {json.dumps(mac)}
Quant signals:   {json.dumps(qnt)}
{mda_section}
Pre-computed values (use these exactly):
  volatility_pct:  {vol_pct}
  composite_score: {composite}  (0-100, >60=high, 30-60=moderate, <30=low)
  composite_trend: {composite_trend}
  data_quality:    {data_quality}

Produce a RiskReport JSON with ALL of these fields:
  ticker, risk_level (low/moderate/high), volatility_pct, pe_ratio (number or 'N/A'),
  summary (one sentence, ground in MD&A language where available),
  recommendation (hold/watch/avoid),
  implied_vol_pct, debt_to_equity, sentiment_score, dominant_theme,
  market_regime, composite_score, data_quality,
  composite_trend (copy the pre-computed string exactly),
  mda_excerpt (key phrase from MD&A that supports your summary, or null)

Use pre-computed volatility_pct and composite_score exactly.
risk_level: <30=low, 30-60=moderate, >60=high
recommendation: hold=low risk, watch=moderate, avoid=high
"""
            llm_result = call_llm_json(system, user, RiskReport, settings, cost)
    except Exception:
        pass

    if llm_result:
        llm_result["composite_trend"] = composite_trend
        state = {**state, "risk_report": llm_result}
    else:
        # Deterministic fallback
        fallback = RiskReport(
            ticker=ticker,
            risk_level=risk_level_from_score(composite),
            volatility_pct=vol_pct,
            pe_ratio=market.get("pe_ratio"),
            summary=(
                f"{ticker} screens as {risk_level_from_score(composite)} risk with composite "
                f"score {composite}/100, driven by {vol_pct}% 52-week range volatility and a "
                f"{regime or 'unknown'} macro regime."
            ),
            recommendation=recommendation_from_score(composite),
            implied_vol_pct=iv_pct,
            debt_to_equity=d_e,
            sentiment_score=sent,
            dominant_theme=news.get("dominant_label") or news.get("sentiment_label"),
            market_regime=regime,
            composite_score=composite,
            data_quality=data_quality,
            composite_trend=composite_trend,
            mda_excerpt=fund.get("mda_excerpt"),
        )
        state = {**state, "risk_report": fallback.model_dump()}

    return state


# ── Node 4: Judge ──────────────────────────────────────────────────────────
def node_judge(state: FinSightState) -> FinSightState:
    settings = state["settings"]
    cost = state["cost"]
    if cost.budget_exceeded or not settings.groq_api_key:
        return {**state, "judge_score": {"score": 3, "reasoning": "Judge skipped."}}

    print("  [judge] Scoring report quality...")
    system = "You are a quality judge for AI-generated financial reports."
    user = f"""
Score this risk report on a scale of 1-5 (5=excellent).
Criteria: completeness, internal consistency, actionability, grounding in data.

Report: {json.dumps(state['risk_report'])}

Return JSON: {{"score": <int 1-5>, "reasoning": "<one sentence>"}}
"""
    result = call_llm_json(system, user, JudgeScore, settings, cost)
    if not result:
        result = {"score": 3, "reasoning": "Judge unavailable."}
    print(f"  [judge] Score: {result.get('score')}/5 — {result.get('reasoning')}")
    return {**state, "judge_score": result}


# ── Routing ────────────────────────────────────────────────────────────────
def route_after_judge(state: FinSightState) -> str:
    cost = state["cost"]
    if cost.budget_exceeded:
        print("  [router] Budget exceeded → finalize")
        return "finalize"
    score = int(state["judge_score"].get("score", 3))
    iters = int(state.get("refinement_iter", 0))
    if score >= JUDGE_THRESHOLD:
        return "hallucination_check"
    if score == 1 or iters >= MAX_REFINEMENT_ITERS:
        print(f"  [router] Score={score}, iters={iters} → finalize")
        return "finalize"
    print(f"  [router] Score={score} below threshold → refining (iter {iters+1})")
    return "refine_report"


# ── Node 5: Refine ─────────────────────────────────────────────────────────
def node_refine_report(state: FinSightState) -> FinSightState:
    settings = state["settings"]
    cost = state["cost"]
    if cost.budget_exceeded:
        return state
    iter_n = state.get("refinement_iter", 0) + 1
    print(f"  [refine_report] Refinement iteration {iter_n}...")
    system = "You are an expert financial analyst. Improve the risk report based on feedback."
    user = f"""
Original report:      {json.dumps(state['risk_report'])}
Judge feedback:       {json.dumps(state['judge_score'])}
Hallucination report: {json.dumps(state.get('hallucination_report', {}))}
Bias report:          {json.dumps(state.get('bias_report', {}))}

Improve the report to address all flagged issues. Keep the same JSON schema.
recommendation must be one of: hold, watch, avoid
The composite_trend field must stay exactly as-is.

Return an improved RiskReport JSON with the same fields.
"""
    result = call_llm_json(system, user, RiskReport, settings, cost)
    if result:
        if state["risk_report"].get("composite_trend"):
            result["composite_trend"] = state["risk_report"]["composite_trend"]
        state = {**state, "risk_report": result}
    return {**state, "refinement_iter": iter_n}


# ── Node 6: Hallucination check ────────────────────────────────────────────
def node_hallucination_check(state: FinSightState) -> FinSightState:
    settings = state["settings"]
    cost = state["cost"]
    print("  [hallucination_check] Running deterministic pre-check...")

    det = deterministic_hallucination_check(
        risk_report=state["risk_report"],
        market_data=state["market_data"],
        iv_data=state["iv_data"],
        fundamentals_data=state["fundamentals_data"],
        news_sentiment_data=state["news_sentiment_data"],
        macro_data=state["macro_data"],
    )

    llm_result = qualitative_hallucination_check(state, settings, cost)
    combined = {
        "has_hallucination": not det.deterministic_check_passed or llm_result.get("has_hallucination", False),
        "flagged_claims": llm_result.get("flagged_claims", []),
        "confidence": llm_result.get("confidence", "high"),
        "deterministic_flags": det.deterministic_flags,
        "deterministic_check_passed": det.deterministic_check_passed,
    }
    if combined["has_hallucination"]:
        print(f"  ⚠ Hallucination detected. Det: {det.deterministic_flags}. LLM: {llm_result.get('flagged_claims')}")
    return {**state, "hallucination_report": combined}


# ── Node 7: Bias audit ─────────────────────────────────────────────────────
def node_bias_audit(state: FinSightState) -> FinSightState:
    settings = state["settings"]
    cost = state["cost"]
    if cost.budget_exceeded:
        return state
    print("  [bias_audit] Checking for sentiment-driven bias...")
    system = "You are a bias auditor for AI-generated financial risk assessments."
    user = f"""
Risk report:    {json.dumps(state['risk_report'])}
News sentiment: {json.dumps({k:v for k,v in state['news_sentiment_data'].get('data', {}).items() if k != 'classifications'})}
Fundamentals:   {json.dumps(state['fundamentals_data'].get('data', {}))}

Flag sentiment_bias_detected=true if the recommendation aligns with sentiment_score direction
but contradicts the fundamentals (e.g. 'watch' with negative sentiment but strong financials).

Return JSON: {{"sentiment_bias_detected": bool, "reasoning": "<one sentence>"}}
"""
    result = call_llm_json(system, user, BiasReport, settings, cost)
    return {**state, "bias_report": result or {"sentiment_bias_detected": False, "reasoning": "Bias audit skipped."}}


# ── Node 8: Finalize ───────────────────────────────────────────────────────
def node_finalize(state: FinSightState) -> FinSightState:
    print("  [finalize] Applying final deterministic gate, compliance filter...")
    rr = state.get("risk_report", {})
    js = state.get("judge_score", {})
    qd = state.get("quant_data", {})
    hr = state.get("hallucination_report", {})
    br = state.get("bias_report", {})

    if rr:
        final_det = deterministic_hallucination_check(
            risk_report=rr,
            market_data=state["market_data"],
            iv_data=state["iv_data"],
            fundamentals_data=state["fundamentals_data"],
            news_sentiment_data=state["news_sentiment_data"],
            macro_data=state["macro_data"],
        )
        existing_flags = hr.get("deterministic_flags", [])
        merged_flags = list(dict.fromkeys(existing_flags + final_det.deterministic_flags))
        hr = {
            **hr,
            "deterministic_check_passed": final_det.deterministic_check_passed,
            "deterministic_flags": merged_flags,
            "has_hallucination": hr.get("has_hallucination", False) or not final_det.deterministic_check_passed,
        }

    md = state["market_data"].get("data", {})
    mac = state["macro_data"].get("data", {})
    risk_emoji = {"low": "🟢", "moderate": "🟡", "high": "🔴"}.get(rr.get("risk_level", ""), "⚪")
    det_status = "✓ Passed" if hr.get("deterministic_check_passed", True) else f"⚠ Failed: {hr.get('deterministic_flags', [])}"

    report_text = f"""FinSight v2 Enhanced Risk Report
{'='*55}
Ticker:            {rr.get('ticker')}
Company:           {md.get('company_name', 'N/A')}
Risk Level:        {risk_emoji} {rr.get('risk_level', '').upper()}
Composite Score:   {rr.get('composite_score')} / 100
Composite Trend:   {rr.get('composite_trend', 'N/A')}
Recommendation:    {rr.get('recommendation', '').upper()}

Summary
{'-'*40}
{rr.get('summary')}

{'MD&A Grounding' if rr.get('mda_excerpt') else ''}
{('-'*40) if rr.get('mda_excerpt') else ''}
{rr.get('mda_excerpt', '') if rr.get('mda_excerpt') else ''}

Market Data
{'-'*40}
Current Price:     ${md.get('current_price', 'N/A')}
52-Week High:      ${md.get('52_week_high', 'N/A')}
52-Week Low:       ${md.get('52_week_low', 'N/A')}
Historical Vol:    {rr.get('volatility_pct')}%
Implied Vol:       {rr.get('implied_vol_pct', 'N/A')}%
P/E Ratio:         {rr.get('pe_ratio', 'N/A')}

Fundamentals
{'-'*40}
Debt/Equity:       {rr.get('debt_to_equity', 'N/A')}

Sentiment & Macro
{'-'*40}
Sentiment Score:   {rr.get('sentiment_score', 'N/A')} (-1 bearish → +1 bullish)
Sentiment Method:  {state['news_sentiment_data'].get('data', {}).get('method', 'N/A')}
Dominant Theme:    {rr.get('dominant_theme', 'N/A')}
Market Regime:     {rr.get('market_regime', 'N/A')}
VIX:               {mac.get('vix', 'N/A')}
10Y Yield:         {mac.get('ten_year_yield_pct', 'N/A')}%

Quant Signals
{'-'*40}
RSI Signal:        {qd.get('rsi_signal', 'N/A')}
Momentum:          {qd.get('momentum_signal', 'N/A')}
Macro-Adjusted:    {qd.get('macro_adjusted_signal', 'N/A')}
Technical Note:    {qd.get('technical_summary', 'N/A')}

Evaluation
{'-'*40}
Judge Score:       {js.get('score')}/5
Judge Reasoning:   {js.get('reasoning')}
Det. Pre-check:    {det_status}
Hallucination:     {'⚠ Detected' if hr.get('has_hallucination') else '✓ None detected'}
Bias Audit:        {'⚠ Bias detected' if br.get('sentiment_bias_detected') else '✓ No bias detected'}
Bias Reasoning:    {br.get('reasoning', 'N/A')}
Data Quality:      {rr.get('data_quality', 'N/A')}
Refinement Iters:  {state.get('refinement_iter', 0)}
Sentiment Method:  {state['news_sentiment_data'].get('data', {}).get('method', 'N/A')}
"""
    report_text, redacted = apply_compliance_filter(report_text)
    if redacted:
        report_text += f"\n[Compliance: redacted {redacted}]"

    return {**state, "hallucination_report": hr, "final_report_text": report_text}


# ── Build LangGraph ────────────────────────────────────────────────────────
def _build_graph():
    builder = StateGraph(FinSightState)
    builder.add_node("collect_data",        node_collect_data)
    builder.add_node("quant_strategy",      node_quant_strategy)
    builder.add_node("risk_synthesis",      node_risk_synthesis)
    builder.add_node("judge",               node_judge)
    builder.add_node("refine_report",       node_refine_report)
    builder.add_node("hallucination_check", node_hallucination_check)
    builder.add_node("bias_audit",          node_bias_audit)
    builder.add_node("finalize",            node_finalize)

    builder.set_entry_point("collect_data")
    builder.add_edge("collect_data",   "quant_strategy")
    builder.add_edge("quant_strategy", "risk_synthesis")
    builder.add_edge("risk_synthesis", "judge")
    builder.add_conditional_edges(
        "judge",
        route_after_judge,
        {
            "hallucination_check": "hallucination_check",
            "refine_report":       "refine_report",
            "finalize":            "finalize",
        },
    )
    builder.add_edge("refine_report",       "judge")
    builder.add_edge("hallucination_check", "bias_audit")
    builder.add_edge("bias_audit",          "finalize")
    builder.add_edge("finalize",            END)
    return builder.compile()


_graph = None

def _get_graph():
    global _graph
    if _graph is None:
        _graph = _build_graph()
    return _graph


# ── Public entry point ─────────────────────────────────────────────────────
def run_finsight_analysis(ticker: str, settings: Settings | None = None) -> RiskAnalysisResult:
    settings = settings or Settings()
    cost = CostTracker(settings.cost_budget_usd)
    ticker = ticker.upper().strip()
    llm = get_llm_client(settings) if settings.groq_api_key else None

    initial_state: FinSightState = {
        "ticker": ticker,
        "settings": settings,
        "cost": cost,
        "llm": llm,
        "market_data": {},
        "iv_data": {},
        "fundamentals_data": {},
        "news_sentiment_data": {},
        "macro_data": {},
        "quant_data": {},
        "risk_report": {},
        "judge_score": {},
        "hallucination_report": {},
        "bias_report": {},
        "refinement_iter": 0,
        "final_report_text": "",
        "errors": [],
        "provider_payloads": {},
    }

    graph = _get_graph()
    final_state = graph.invoke(initial_state)

    try:
        save_report(
            final_state["ticker"],
            final_state["risk_report"],
            final_state.get("judge_score", {}),
            token_cost=cost.input_tokens + cost.output_tokens,
        )
        try:
            chroma_store_report(final_state["ticker"], final_state["risk_report"])
        except Exception:
            pass
    except Exception as exc:
        final_state["errors"].append(f"persistence: {exc}")

    report = RiskReport(**final_state["risk_report"])
    data_quality = report.data_quality
    status = "success" if data_quality == "full" and not final_state["errors"] else "partial"
    if final_state["market_data"].get("status") == "error":
        status = "failed"

    result = RiskAnalysisResult(
        ticker=ticker,
        status=status,
        data_quality=data_quality,
        metrics=_metrics_from_report(report),
        risk_report=report,
        quant_data=QuantData(**final_state["quant_data"]) if final_state.get("quant_data") else None,
        judge_score=JudgeScore(**final_state["judge_score"]) if final_state.get("judge_score") else None,
        hallucination_report=HallucinationReport(**final_state["hallucination_report"]) if final_state.get("hallucination_report") else None,
        bias_report=BiasReport(**final_state["bias_report"]) if final_state.get("bias_report") else None,
        validation=ValidationResult(**final_state["hallucination_report"]) if final_state.get("hallucination_report") else ValidationResult(),
        sources=_sources_from_payloads(final_state.get("provider_payloads", {})),
        provider_payloads=final_state.get("provider_payloads", {}),
        errors=final_state["errors"],
        cost=cost.summary(),
    )
    result.final_report_text = final_state.get("final_report_text", "")
    return result


def _metrics_from_report(report: RiskReport) -> dict[str, Any]:
    return {
        "volatility_pct": report.volatility_pct,
        "implied_vol_pct": report.implied_vol_pct,
        "debt_to_equity": report.debt_to_equity,
        "sentiment_score": report.sentiment_score,
        "market_regime": report.market_regime,
        "composite_score": report.composite_score,
        "risk_level": report.risk_level,
        "score_breakdown": score_breakdown(
            report.volatility_pct,
            report.implied_vol_pct,
            report.debt_to_equity,
            report.sentiment_score,
            report.market_regime,
        ),
    }


def _sources_from_payloads(payloads: dict[str, ProviderPayload]) -> list[SourceRef]:
    sources = [SourceRef(name="Yahoo Finance", metadata={"providers": ["market", "options"]})]
    sec = payloads.get("fundamentals_data", ProviderPayload(status="skipped")).data
    if sec.get("filing_url"):
        sources.append(SourceRef(
            name="SEC EDGAR",
            url=sec["filing_url"],
            metadata={
                "cik": sec.get("cik"),
                "accession_number": sec.get("accession_number"),
                "file_date": sec.get("file_date"),
                "period_of_report": sec.get("period_of_report"),
            },
        ))
    news = payloads.get("news_sentiment_data", ProviderPayload(status="skipped"))
    if news.status == "success":
        sources.append(SourceRef(name="GNews", metadata={"method": news.data.get("method")}))
    sources.append(SourceRef(name="Yahoo Finance", metadata={"providers": ["macro"]}))
    return sources